"""initial_schema

Revision ID: 695619ad8629
Revises: 
Create Date: 2026-04-01 23:41:36.077991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695619ad8629'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_field_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_tracker_field_scope_key')
    )
    with op.batch_alter_table('tracker_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracker_field_definitions_scope'), ['scope'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('end_time', sa.String(length=32), nullable=True),
    sa.Column('event', sa.Text(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('contentment', sa.Integer(), nullable=True),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('music', sa.String(length=64), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.String(length=16), server_default=sa.text("'manual'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_log_entries_user_log_date', ['user_id', 'log_date'], unique=False)

    op.create_table('tracker_days',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'log_date')
    )
    op.create_table('tracker_select_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['tracker_field_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracker_select_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracker_select_options_field_definition_id'), ['field_definition_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker_select_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_select_options_field_definition_id'))

    op.drop_table('tracker_select_options')
    op.drop_table('tracker_days')
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_log_entries_user_log_date')
        batch_op.drop_index(batch_op.f('ix_log_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_log_date'))

    op.drop_table('log_entries')
    op.drop_table('users')
    with op.batch_alter_table('tracker_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracker_field_definitions_scope'))

    op.drop_table('tracker_field_definitions')
    # ### end Alembic commands ###
